### PR TITLE
Adds utility script to prepopulate cache (closes #28).

### LINKED ISSUE #28: Develop strategies for prepopulating cache.
We should write a command that prepopulates the cache based on some combination of a list of common/popular searches and short combinations of characters.

### PR DESCRIPTION
**Pull request by chuckharmston**
- [x] Remove coverage from `run.sh`
- [x] Test for `recommendation.tasks.task_recommend.make_key`
- [x] Test for `prepopulate.explode`
- [x] Test for `prepopulate.queue`
- [x] Test for `prepopulate.wikipedia`
- [x] Test for `prepopulate.alexa`

### CODE REVIEW

**Comment by chuckharmston** [comment]
screen shot 2016-04-18 at 5 05 46 pm

This is pretty neat, though.

**Comment by chuckharmston** [comment]
No longer WIP!

r? @6a68

**Comment by 6a68** [comment]
@chuckharmston Looks good to me overall, tests passing for me locally.

Any reason we aren't using the Alexa US top 1000? We're just targeting en-US for the initial release.

Needs a rebase, then feel free to merge.

**Comment by chuckharmston** [comment]
I used what @nchapman suggested in the bug; easy to tweak. I'd file a followup bug, but in a quick search I couldn't find any US-specific raw data sources.

**Pull request merged**
