### PR TITLE
Refactors into single-container application with supplementary services in compose (closes #51).

### LINKED ISSUE #51: Refactor to Dockerflow-compliant single-container application.
The original plan was to use a multiple-container Docker configuration and use one of AWS' services that allow multiple-container deployment. That's changed, and we've now been asked to use [Dockerflow](https://github.com/mozilla-services/Dockerflow), which is a substantial departure. I've tried to reuse as much work as possible, but there have been enough gotchas that I've talked myself into starting over with the production architecture in mind.

This bug will track design efforts, and bugs resulting from it will be tracked in the [Deployment-ready milestone](https://github.com/mozilla/universal-search-recommendation/milestones/Deployment-ready).

### Desired end state:

- On successful builds on `master`, CI will build the application into a Docker container that is then published to Docker Hub and deployed.
- The built container is [Dockerflow](https://github.com/mozilla-services/Dockerflow)-compliant.
- Local development is as contributor-friendly as possible.

### Proposal:

- Refactor from a multiple-container configuration to a single-container one that only manages the application.
- For local development, use a [Compose](https://docs.docker.com/compose/) configuration that manages data storage and task queues.
- Eliminate nginx entirely; use uWSGI directly as a server, and use Flask's [`send-file`](http://flask.pocoo.org/docs/0.10/api/#flask.send_file) for our few static files.

Feedback wanted: @mostlygeek @6a68

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @6a68

### CODE REVIEW

**Comment by chuckharmston** [comment]
CI won't like this.

**Comment by chuckharmston** [comment]
CI fixed! This is ready for review and merge, if appropriate.

**Comment by 6a68** [comment]
@chuckharmston The local docs are really nice. Got it working on the first pass!

I'm seeing a 500 error when I surf to universal-search.dev, but I think it might be my local setup; I'll give it another try in the morning, and ping you / file a bug if I can repro the error.

:+1: Feel free to merge after rebasing.

**Comment by chuckharmston** [comment]
Ah, I think I know why: the local docs I linked earlier were pinned to a commit that had a faulty command. 

Updated: https://github.com/chuckharmston/universal-search-recommendation/blob/51-single-container/docs/local.md

If you stop the container:

```bash
docker stop $(docker ps --filter ancestor="universal-search-recommendation" --format="{{.ID}}")
```

And start it back up again with an updated command:

```bash
docker run -d -e "RECOMMENDATION_SERVICES=`docker-machine ip universal-search-dev`" -p 80:8000/tcp universal-search-recommendation
```

I bet it's working.

**Comment by 6a68** [comment]
Cool, trying now

**Comment by 6a68** [comment]
@chuckharmston Yup, that was it:

screen shot 2016-02-26 at 10 21 16 am

Merge at will!

**Comment by chuckharmston** [comment]
Thanks Jared!

**Pull request merged**
