### PR TITLE
Adds socket timeout to Celery broker (connected to #92).

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @mostlygeek

### CODE REVIEW

**Comment by 6a68** [comment]
@chuckharmston R+ from me. You might want to tell coveralls to ignore the new config file, but this seems good to merge

**Comment by mostlygeek** [comment]
Can this be an environmental variable? It would make it easier to test as well we can set it to 10seconds and see if it closes extra connections.

**Comment by mostlygeek** [comment]
Sort of hacked the config into the stage server's running container. This PR doesn't fix #92. The number of connections continues to grow.

**Comment by chuckharmston** [comment]
Now exposes all 3 of the Celery settings as environment variables, with defaults equal to their various software packages'. 

r? @mostlygeek

**Comment by chuckharmston** [comment]
> Sort of hacked the config into the stage server's running container. This PR doesn't fix #92. The number of connections continues to grow.

I'm pretty sure the configuration is read once on startup and held in memory; I don't think that randomly changing a file or environment variable will change anything without rebooting the workers.

**Comment by mostlygeek** [comment]
> I'm pretty sure the configuration is read once on startup and held in memory; I don't think that randomly changing a file or environment variable will change anything without rebooting the workers.

I made this celeryconfig.py: 

```python
BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 10,
    'max_connections': 5,
}
CELERY_REDIS_MAX_CONNECTIONS = 10
```

and directly volume mounted it into a new container: 

```bash
> sudo docker run -it --rm=true --net host -e PORT=8000 --env-file /etc/dockerflow/env_vars.txt -v "$HOME/celeryconfig.py:/app/recommendation/celeryconfig.py" hub.prod.mozaws.net/mozilla/universal-search-recommendation:2015.03.30
```

To the app, `celeryconfig.py` is there. It had no effect on the number of growing connections.

**Comment by mostlygeek** [comment]
Also it's mainly the web app that's affected, when __heartbeat__ is checked. The workers stay at a pretty constant number of connections.

**Comment by chuckharmston** [comment]
@mostlygeek If you insist that those settings are being applied and don't work, I'm out of configuration-related ideas. I'll close this PR and move conversation back to the bug.

**Pull request closed without merging**
