### PR TITLE
Fixes Redis connection leak in heartbeat ping (closes #92):

### LINKED ISSUE #92: Web server creates but does not close redis connections
I got a pagerduty alert. Investigating found that there were thousands of connections open to the redis server:

```bash
> netstat -aln | grep 6379 | wc -l
28232
```

In the logs I see: 

```
...
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: sock.connect(socket_address)
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: OSError: [Errno 99] Cannot assign requested address
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: During handling of the above exception, another exception occurred:
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: Traceback (most recent call last):
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 572, in execute_command
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: connection.send_command(*args)
...
```

The important line in the log is: `OSError: [Errno 99] Cannot assign requested address`

This is a OS / kernel error that comes up when no more connections to an IP can be made. Most likely this is the result of the `__heartbeat__` endpoint being monitored and it opens but doesn't close connections to redis.

### PR DESCRIPTION
**Pull request by chuckharmston**
screen shot 2016-04-13 at 7 14 02 pm

Setting Celery's `BROKER_POOL_LIMIT` to `0`, effectively disabling connection pooling, appears to fix this problem. I'm not sure what happened in @mostlygeek's testing [when I initially suggested this](https://github.com/mozilla/universal-search-recommendation/issues/92#issuecomment-207496974), but my guess is that the settings weren't applied correctly.

In the process of debugging I refactored to ping Redis directly. This is more reliable and a better separation of concerns than relying on Celery to do it for us, so I left it here.

Ops note: when deploying these changes, `REDIS_HOST`, `REDIS_PORT`, and `REDIS_DB` need to be set individually. `CELERY_BROKER_URL` no longer needs to be set.

r? @6a68 @mostlygeek

### CODE REVIEW

**Comment by 6a68** [comment]
This fix is suggested in a number of issues filed against the celery repo. I'm glad it helped in our case too. Merging.

**Comment by mostlygeek** [comment]
> Setting Celery's BROKER_POOL_LIMIT to 0, effectively disabling connection pooling, appears to fix this problem. I'm not sure what happened in @mostlygeek's testing when I initially suggested this, but my guess is that the settings weren't applied correctly.

Just tested this and the issue still exists. Using the [same test method](https://github.com/mozilla/universal-search-recommendation/pull/93#issuecomment-209614340) as before I created a celeryconfig.py and volume mounted it into a container. 

The tests still show connections being opened but never closed. 

At this point I don't think it's safe to assume that disabling connection pooling is the correct fix for the issue until we can reproduce a fix reliably. 

Also, I don't know why it works differently on your localhost than it does on AWS.

**Comment by chuckharmston** [comment]
@mostlygeek Using the way you're hacking it together, can you please confirm that Celery is discovering and loading the preferences correctly? You can do that this way from a Python prompt inside of the app container:

    >>> from recommendation.factory import create_queue
    >>> create_queue().conf['BROKER_POOL_LIMIT']

I was eventually able to reproduce locally, and this did fix the problem. I'd be happy to screencap it with and without the fix if you aren't convinced.

> How are you running it locally? 

I'm running it using our normal local development setup, as documented here: https://github.com/mozilla/universal-search-recommendation/blob/master/docs/local.md. I'm running my manual tests by adding `net-tools` to the `apt-get` installs in the Dockerfile, rebulding, and running this while shelled into the app container:

    while true; do netstat -aln | grep 6379 | grep ESTAB | wc -l; sleep 1; done

Simultaneously, I'm pinging the heartbeat endpoint every second from outside of the container this way:

    watch -n1 curl http://universal-search.dev/__heartbeat__

I just ran it for 3 hours, and never once did it go above 3 open connections. On master before this was merged, it steadily increases, as you have been observing when deployed.

**Comment by chuckharmston** [comment]
Here's that video: https://chchc.ch/DkDEjD

I tried to make it clear what I'm doing, but the essence of it:

1. On master, build the app container and start it up alongside the various services that coexist in a compose file.
2. Hit the heartbeat endpoint every second using `watch`. This never stops throughout the rest of the video; you can watch it stop being able to connect to the server while rebuilding the app container.
3. SSH into the app container, run the `netstat` command you provided on a loop.
4. Observe that the number of open Redis connections is growing.
5. Check out 3fe31c8, the commit for this PR.
6. Kill the app container, rebuild it with the code from this branch, and run it.
7. Reboot the services for good measure.
8. #3 again, only in the newly-build app container.
9. Observe that number of open Redis connections is consistently less than 3.

**Pull request merged**
