### PR TITLE
Fix #92 __heartbeat__ opens but never closes connections

### LINKED ISSUE #92: Web server creates but does not close redis connections
I got a pagerduty alert. Investigating found that there were thousands of connections open to the redis server:

```bash
> netstat -aln | grep 6379 | wc -l
28232
```

In the logs I see: 

```
...
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: sock.connect(socket_address)
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: OSError: [Errno 99] Cannot assign requested address
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: During handling of the above exception, another exception occurred:
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: Traceback (most recent call last):
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 572, in execute_command
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: connection.send_command(*args)
...
```

The important line in the log is: `OSError: [Errno 99] Cannot assign requested address`

This is a OS / kernel error that comes up when no more connections to an IP can be made. Most likely this is the result of the `__heartbeat__` endpoint being monitored and it opens but doesn't close connections to redis.

### PR DESCRIPTION
**Pull request by mostlygeek**
This fix uses a shared Celery app instance for testing state of
dependent services. After testing the celery app's
connections are explicitly closed.

Notes on cause:
- the `redis_status()` and `celery_status()` checks create new Celery
  application instances on every test
- the Celery application instances opens up connections to redis but
  these connections are never closed.
- I'm assuming that because the connections are never closed, python
  never GC's them, so they stick around forever

### CODE REVIEW

**Comment by chuckharmston** [comment]
The thing I don't understand: why wouldn't adding a socket timeout to Redis cause the connection to close? That should allow the celery app to be collected.

**Comment by 6a68** [comment]
I don't see how this patch would resolve the underlying issue. If Celery doesn't properly close Redis connections, then it will crash after a few thousand jobs are created--it doesn't matter if it's due to the heartbeat method, or due to user keystrokes that have been sent to the server.

**Comment by mostlygeek** [comment]
I haven't dug deeply but does the code create a new celery app instance per http request?

It seems that the celery app instances try to hold their connections as long as possible and creating lots of them will eventually lead to resource exhaustion.

**Comment by 6a68** [comment]
I think we might want to explore other configuration changes before trying to land any workaround patches.

Based on looking through the celery github issue tracker, many connection pooling problems / deadlocks seem to be solved by adjusting configuration values: either disabling connection pooling, by setting `BROKER_POOL_LIMIT=0`, or disabling task prefetching, by passing the `-Ofair` option.

[Here](https://github.com/celery/celery/issues/2991) is a Celery connection pooling bug that affected RabbitMQ--the problems aren't confined to Celery + Redis. It was reportedly solved by setting `BROKER_POOL_LIMIT=0`, see docs [here](http://docs.celeryproject.org/en/latest/configuration.html#std:setting-BROKER_POOL_LIMIT).

[Here](https://github.com/celery/celery/issues/2464) is a similar Celery-Redis deadlock bug, reportedly fixed by disabling "prefetch" behavior in the workers. Passing the `-Ofair` option at the command line is discussed in the docs [here](http://celery.readthedocs.org/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings).

**Comment by 6a68** [comment]
I'll copy that last comment over to the parent bug.

**Comment by mostlygeek** [comment]
I'm OK closing this PR and shipping with connection pooling disabled. Though, if we ever enable it we might see the same behavior again. I tested `:latest` on the stage server with `BROKER_POOL_LIMIT = 10` and the socket use behavior does still occur.

**Comment by chuckharmston** [comment]
I wouldn't dismiss the possibility of an application error causing too handily—it seems like disabling connection pooling is a solution that addresses the symptoms but not the cause—I'd just like to have my head around what the problem actually is.

I'm still stuck on why, if this addresses the problem, that setting a reasonable timeout on Redis socket timeouts wouldn't fix the problem.

But we've spent a lot of time on this; I'd happily merge this patch if it works, the build passes, and then we can all move on with our lives :smile:

**Comment by mostlygeek** [comment]
> But we've spent a lot of time on this; I'd happily merge this patch if it works, the build passes, and then we can all move on with our lives :smile:

Me too!

Would you be ok if I reverted #94 in this PR (if I can get the tests to pass)?

**Comment by chuckharmston** [comment]
Totally fine. Would you mind keeping that as a separate commit, while squashing the rest?

**Comment by mostlygeek** [comment]
Yup! Let me work on this this afternoon.

**Comment by 6a68** [comment]
> I tested the :latest docker image on the stage server with BROKER_POOL_LIMIT = 10 and the socket use behavior does occur. 

Yeah, the workaround is to completely disable Celery's pooling by setting BROKER_POOL_LIMIT=0.

**Comment by 6a68** [comment]
Sounds like chuck was fine with this approach, tests passing, LGTM, so let's give it a spin. Merging

**Comment by mostlygeek** [comment]
Tested on staging box with a light load test. The number of redis connections stays fairly constant. Ship it!

**Comment by wresuolc** [comment]
Thanks for sorting this out! :love_hotel:

**Pull request merged**
